#!/usr/bin/env python3
"""Public per-topic spoken-script checkpoint helpers."""
from __future__ import annotations

import hashlib
import json
import os
import zipfile
from pathlib import Path
from typing import Any

from daily_workflow import WorkflowConflict, canonical


RUNTIME_SCHEMA_VERSION = 3
MATERIAL_FAILURE_REASONS = frozenset({
    "material_or_angle_insufficiency",
    "material_insufficiency",  # legacy input accepted, never generated by the new contract
})
DEFAULT_PRIVATE_CONTEXT_ALLOWLIST = (
    Path(__file__).resolve().parents[1]
    / "config"
    / "web010_austin_private_context_allowlist.json"
)

_DEFAULT_PRIVATE_SKILL_ROOT = (
    Path.home()
    / ".codex"
    / "skills"
    / "austin-voice-scriptwriter"
)

DIRECT_WRITER_STAGE_CONTRACT = {
    "schema_version": 1,
    "topology": "one_automation_codex_direct_writer_stage_per_selected_topic",
    "input_scope": [
        "one_same_run_rich_topic_card",
        "austin_thesis_audience_conflict_and_why_now",
        "model_owned_evidence_boundary",
        "source_facts_and_details",
        "fact_boundary",
        "cannot_claim",
        "short_selection_reason",
        "substantive_editorial_judgment",
    ],
    "skills": [
        "austin-voice-scriptwriter",
    ],
    "private_authority": "automation_codex_reads_approved_writer_authority_transiently",
    "previous_topic_body": "forbidden",
    "other_topic_identity": "forbidden",
    "editorial_batch_deliberation": "forbidden",
    "recursive_model_execution": "forbidden",
    "raw_text_persistence": "forbidden",
}

# Checkpoints written by f68bf927 may still carry the superseded two-skill
# snapshot. It is accepted only while resuming that historical checkpoint; all
# newly emitted packets use DIRECT_WRITER_STAGE_CONTRACT above.
LEGACY_WRITER_CHILD_SNAPSHOT = {
    "schema_version": 1,
    "topology": "one_fresh_bounded_writer_child_per_selected_topic",
    "skills": [
        "austin-no-overtime-scripting",
        "austin-voice-scriptwriter",
    ],
    "private_authority": "writer_child_reads_allowlist_transiently",
    "previous_topic_body": "forbidden",
    "other_topic_identity": "forbidden",
    "editorial_batch_deliberation": "forbidden",
    "recursive_child_execution": "forbidden",
    "raw_text_persistence": "forbidden",
}

# A task may resume an in-progress checkpoint created by the immediately
# previous per-topic runtime. It still has no private text or script body, so
# accepting this safe snapshot does not reopen the retired batch path.
LEGACY_COMPATIBILITY_SNAPSHOT = {
    "schema_version": 1,
    "phase_order": ["facts_first_draft", "austin_author_edit"],
    "facts_first_private_context": "forbidden_until_draft_complete",
    "author_edit_after_draft": "draft_complete",
    "raw_text_persistence": "forbidden",
}


def _default_context_paths() -> dict[str, Path]:
    skill_root = _DEFAULT_PRIVATE_SKILL_ROOT
    workspace = Path(__file__).resolve().parents[2]
    production_root = workspace / "ai_account_radar" / "output" / "runs"
    return {
        "AUSTIN_PRIVATE_REFERENCE_ROOT": skill_root / "references" / "private",
        "AUSTIN_CASE_REFERENCE_FILE": skill_root / "examples" / "private" / "full_topic_cards.json",
        "AUSTIN_PROJECT_ROOT": workspace,
        "AUSTIN_APPROVED_SCRIPT_MVP": (
            production_root / "run_20260805_080110" / "scripts"
            / "0f51191cbf21c6b2677f.md"
        ),
        "AUSTIN_APPROVED_SCRIPT_DIRECTOR": (
            production_root / "run_20260803_110453" / "scripts"
            / "b4cf842748e23795e5c9.md"
        ),
    }


def _context_allowlist(path: str | Path | None = None) -> dict[str, Any]:
    source = Path(
        path
        or os.environ.get("AUSTIN_PRIVATE_CONTEXT_ALLOWLIST", DEFAULT_PRIVATE_CONTEXT_ALLOWLIST)
    )
    try:
        value = json.loads(source.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise WorkflowConflict("austin_private_context_allowlist_unreadable") from error
    allowed_roles = {
        "user_persona", "user_original_cases", "user_original_case_cards",
        "user_original_sample", "user_original_edit_pairs",
        "approved_austin_script_module",
    }
    if (
        not isinstance(value, dict)
        or value.get("schema_version") != 1
        or not value.get("allowlist_id")
        or not isinstance(value.get("sources"), list)
    ):
        raise WorkflowConflict("austin_private_context_allowlist_invalid")
    seen: set[str] = set()
    for source_row in value["sources"]:
        if not isinstance(source_row, dict):
            raise WorkflowConflict("austin_private_context_source_invalid")
        source_id = str(source_row.get("source_id") or "")
        role = str(source_row.get("role") or "")
        excerpt_ids = source_row.get("excerpt_ids")
        if (
            not source_id or source_id in seen or role not in allowed_roles
            or not source_row.get("path_env")
            or not isinstance(excerpt_ids, list)
            or not excerpt_ids
            or any(not isinstance(item, str) or not item for item in excerpt_ids)
            or source_row.get("kind") not in {"text", "json", "docx"}
        ):
            raise WorkflowConflict("austin_private_context_source_invalid")
        seen.add(source_id)
    return value


def _resolve_context_path(source_row: dict[str, Any]) -> Path:
    defaults = _default_context_paths()
    path_env = str(source_row["path_env"])
    base_value = os.environ.get(path_env)
    if base_value is None:
        default = defaults.get(path_env)
        if default is None:
            raise WorkflowConflict("austin_private_context_path_unbound")
        base = default
    else:
        base = Path(base_value)
    relative = str(source_row.get("relative_path") or "")
    return base / relative if relative else base


def _authority_sources(
    allowlist: dict[str, Any],
) -> list[tuple[dict[str, Any], Path]]:
    return [
        (source_row, _resolve_context_path(source_row))
        for source_row in allowlist["sources"]
    ]


def load_austin_authority(
    private_root: str | Path | None = None,
    case_file: str | Path | None = None,
    project_root: str | Path | None = None,
    allowlist_path: str | Path | None = None,
) -> dict[str, Any]:
    """Verify the allowlist and return safe provenance; raw text stays transient."""
    overrides = {
        "AUSTIN_PRIVATE_REFERENCE_ROOT": private_root,
        "AUSTIN_CASE_REFERENCE_FILE": case_file,
        "AUSTIN_PROJECT_ROOT": project_root,
    }
    previous: dict[str, str | None] = {}
    for key, value in overrides.items():
        if value is not None:
            previous[key] = os.environ.get(key)
            os.environ[key] = str(value)
    ledger: list[dict[str, str]] = []
    try:
        allowlist = _context_allowlist(allowlist_path)
        for source_row, source in _authority_sources(allowlist):
            source_id = str(source_row["source_id"])
            role = str(source_row["role"])
            kind = str(source_row["kind"])
            try:
                raw = source.read_bytes()
                if not raw:
                    raise ValueError("empty")
                if kind == "text":
                    raw.decode("utf-8")
                elif kind == "json":
                    json.loads(raw.decode("utf-8"))
                else:
                    with zipfile.ZipFile(source) as archive:
                        archive.read("word/document.xml")
            except (OSError, UnicodeDecodeError, ValueError, json.JSONDecodeError) as error:
                raise WorkflowConflict("austin_reference_runtime_read_failed") from error
            except (KeyError, zipfile.BadZipFile) as error:
                raise WorkflowConflict("austin_reference_runtime_read_failed") from error
            ledger.append({
                "source_id": source_id,
                "role": role,
                "sha256": hashlib.sha256(raw).hexdigest(),
                "read_status": "read",
                "excerpt_ids": ",".join(str(item) for item in source_row["excerpt_ids"]),
            })
    finally:
        for key, value in previous.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value
    return {
        "read_status": "complete",
        "allowlist_id": allowlist["allowlist_id"],
        "sources": ledger,
        "outer_codex_direct_read_required": True,
        "raw_text_in_runtime_output": False,
    }


def load_writer_contract() -> dict[str, Any]:
    """Return the direct writer-stage contract without reading private source."""
    return json.loads(json.dumps(DIRECT_WRITER_STAGE_CONTRACT, ensure_ascii=False))


def selected_topic_ids(selected_topics: list[dict[str, Any]]) -> list[str]:
    identities = [str(row.get("topic_id") or "") for row in selected_topics]
    if not identities or any(not identity for identity in identities):
        raise WorkflowConflict("scripts_selected_topics_invalid")
    if len(identities) != len(set(identities)):
        raise WorkflowConflict("scripts_selected_topics_duplicate")
    return identities


def _writing_contract_snapshot(contract: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema_version": contract["schema_version"],
        "topology": contract["topology"],
        "skills": list(contract["skills"]),
        "private_authority": contract["private_authority"],
        "previous_topic_body": contract["previous_topic_body"],
        "other_topic_identity": contract["other_topic_identity"],
        "recursive_model_execution": contract["recursive_model_execution"],
        "raw_text_persistence": contract["raw_text_persistence"],
    }


def new_checkpoint(
    run_id: str,
    business_date: str,
    selected_topics: list[dict[str, Any]],
    writer_contract: dict[str, Any],
) -> dict[str, Any]:
    return {
        "schema_version": RUNTIME_SCHEMA_VERSION,
        "run_id": run_id,
        "business_date": business_date,
        "stage": "scripts",
        "status": "in_progress",
        "selected_topic_ids": selected_topic_ids(selected_topics),
        "selected_count": len(selected_topics),
        "completed_items": [],
        "writing_contract": _writing_contract_snapshot(writer_contract),
    }


def _validate_script(script: Any, topic_id: str) -> dict[str, str]:
    if not isinstance(script, dict) or set(script) != {
        "topic_id", "title", "hook", "structure", "body",
    }:
        raise WorkflowConflict("script_topic_submission_schema_invalid")
    if script.get("topic_id") != topic_id:
        raise WorkflowConflict("script_topic_not_current")
    if not all(str(script.get(key) or "").strip() for key in (
        "title", "hook", "structure", "body",
    )):
        raise WorkflowConflict("script_topic_submission_incomplete")
    return {key: str(script[key]) for key in (
        "topic_id", "title", "hook", "structure", "body",
    )}


def _validate_failure(failure: Any, topic_id: str) -> dict[str, str]:
    if not isinstance(failure, dict) or set(failure) != {"topic_id", "reason", "detail"}:
        raise WorkflowConflict("script_topic_failure_schema_invalid")
    if failure.get("topic_id") != topic_id:
        raise WorkflowConflict("script_topic_not_current")
    if failure.get("reason") not in MATERIAL_FAILURE_REASONS:
        raise WorkflowConflict("script_topic_failure_reason_invalid")
    if not str(failure.get("detail") or "").strip():
        raise WorkflowConflict("script_topic_failure_incomplete")
    return {
        "topic_id": str(failure["topic_id"]),
        "reason": "material_or_angle_insufficiency",
        "detail": str(failure["detail"]),
    }


def _validate_completed_items(
    items: Any,
    selected_ids: list[str],
) -> None:
    if not isinstance(items, list):
        raise WorkflowConflict("scripts_checkpoint_shape_invalid")
    selected = set(selected_ids)
    seen: set[str] = set()
    for item in items:
        if not isinstance(item, dict) or set(item) not in ({"kind", "topic_id", "script"}, {"kind", "topic_id", "failure"}):
            raise WorkflowConflict("scripts_checkpoint_item_invalid")
        topic_id = str(item.get("topic_id") or "")
        if topic_id not in selected or topic_id in seen:
            raise WorkflowConflict("scripts_checkpoint_item_identity_conflict")
        if item.get("kind") == "script":
            _validate_script(item.get("script"), topic_id)
        elif item.get("kind") == "failure":
            _validate_failure(item.get("failure"), topic_id)
        else:
            raise WorkflowConflict("scripts_checkpoint_item_kind_invalid")
        seen.add(topic_id)


def validate_checkpoint(
    checkpoint: dict[str, Any],
    run_id: str,
    business_date: str,
    selected_topics: list[dict[str, Any]],
    writer_contract: dict[str, Any],
) -> None:
    if "current_reference_selection" in checkpoint or "reference_selection" in checkpoint:
        raise WorkflowConflict("scripts_checkpoint_selector_retired")
    if (
        checkpoint.get("schema_version") not in {2, RUNTIME_SCHEMA_VERSION}
        or checkpoint.get("run_id") != run_id
        or checkpoint.get("business_date") != business_date
        or checkpoint.get("stage") != "scripts"
        or checkpoint.get("status") != "in_progress"
    ):
        raise WorkflowConflict("scripts_checkpoint_identity_conflict")
    if checkpoint.get("selected_topic_ids") != selected_topic_ids(selected_topics):
        raise WorkflowConflict("scripts_checkpoint_selection_conflict")
    contract = checkpoint.get("writing_contract")
    if contract is None:
        # A pre-reset in-progress checkpoint may still carry the old safe metadata.
        # It is accepted for resume, but the next packet uses the direct-stage contract.
        legacy = checkpoint.get("editing_reference")
        if checkpoint.get("schema_version") not in {2, RUNTIME_SCHEMA_VERSION} or not isinstance(legacy, dict):
            raise WorkflowConflict("scripts_checkpoint_writing_contract_conflict")
    elif contract not in (
        _writing_contract_snapshot(writer_contract),
        LEGACY_WRITER_CHILD_SNAPSHOT,
        LEGACY_COMPATIBILITY_SNAPSHOT,
    ):
        raise WorkflowConflict("scripts_checkpoint_writing_contract_conflict")
    _validate_completed_items(checkpoint.get("completed_items"), checkpoint["selected_topic_ids"])


def ensure_checkpoint(
    workflow: Any,
    run_id: str,
    business_date: str,
    selected_topics: list[dict[str, Any]],
    writer_contract: dict[str, Any],
) -> dict[str, Any]:
    existing = workflow.stage(run_id, "scripts")
    if existing is None:
        checkpoint = new_checkpoint(run_id, business_date, selected_topics, writer_contract)
        workflow.commit_stage(run_id, "scripts", checkpoint, "in_progress")
        return checkpoint
    if existing.get("status") != "in_progress":
        raise WorkflowConflict("scripts_checkpoint_not_in_progress")
    checkpoint = existing["payload"]
    validate_checkpoint(checkpoint, run_id, business_date, selected_topics, writer_contract)
    return checkpoint


def first_unfinished_index(checkpoint: dict[str, Any]) -> int:
    completed = {
        str(row.get("topic_id") or "")
        for row in checkpoint.get("completed_items", [])
    }
    for index, identity in enumerate(checkpoint["selected_topic_ids"]):
        if identity not in completed:
            return index
    return len(checkpoint["selected_topic_ids"])


def _packet_id(
    run_id: str,
    business_date: str,
    topic: dict[str, Any],
) -> str:
    basis = {
        "run_id": run_id,
        "business_date": business_date,
        "topic": topic,
    }
    return hashlib.sha256(canonical(basis).encode("utf-8")).hexdigest()


def topic_packet(
    run_id: str,
    business_date: str,
    topic: dict[str, Any],
    index: int,
    selected_count: int,
    completed_count: int,
    writer_contract: dict[str, Any],
) -> dict[str, Any]:
    packet_id = _packet_id(run_id, business_date, topic)
    return {
        "ok": True,
        "action": "scripts_required",
        "stage": "scripts",
        "status": "waiting",
        "run_id": run_id,
        "business_date": business_date,
        "selected_topics": [topic],
        "topic_index": index,
        "selected_count": selected_count,
        "completed_count": completed_count,
        "remaining_count": selected_count - completed_count,
        "next_topic_not_exposed_until_submit": True,
        "topic_input": {
            "packet_id": packet_id,
            "topic_id": topic["topic_id"],
            "writer_owns_final_fields": ["title", "hook", "structure", "body"],
            "current_topic_only": True,
            "previous_topic_body_included": False,
        },
        "writing_contract": _writing_contract_snapshot(writer_contract),
        "required_script_input": {
            "keys": ["packet_id", "script"],
            "failure_keys": ["packet_id", "failure"],
            "script_keys": ["topic_id", "title", "hook", "structure", "body"],
            "current_topic_only": True,
            "material_or_angle_insufficiency_is_item_local": True,
        },
    }


def sanitize_handoff(value: dict[str, Any]) -> dict[str, Any]:
    """Keep persisted handoffs free of retired selector/style/private-routing fields."""
    document = json.loads(json.dumps(value, ensure_ascii=False))
    if document.get("action") != "scripts_required":
        return document
    for key in (
        "voice_pack", "reference_selection", "topic_selector_input",
        "private_style_context", "private_case_catalog", "persona_catalog",
        "approved_exemplar_catalog", "editing_reference", "editing_reference_sha256",
        "editing_reference_content_bytes", "editing_reference_contract",
    ):
        document.pop(key, None)
    topic_input = document.get("topic_input")
    if isinstance(topic_input, dict):
        for key in (
            "voice_pack", "reference_selection", "private_style_context",
            "private_excerpts", "approved_full_scripts", "austin_private_context_raw",
            "austin_authority_read", "austin_private_context", "semantic_reread",
            "editing_reference", "editing_reference_sha256", "editing_reference_contract",
        ):
            topic_input.pop(key, None)
    return document


def submit_topic(
    workflow: Any,
    run_id: str,
    business_date: str,
    selected_topics: list[dict[str, Any]],
    checkpoint: dict[str, Any],
    writer_contract: dict[str, Any],
    submitted: dict[str, Any],
) -> dict[str, Any]:
    validate_checkpoint(checkpoint, run_id, business_date, selected_topics, writer_contract)
    index = first_unfinished_index(checkpoint)
    if index >= len(selected_topics):
        raise WorkflowConflict("scripts_checkpoint_already_complete")
    if not isinstance(submitted, dict):
        raise WorkflowConflict("script_topic_submission_schema_invalid")
    valid_script_shape = set(submitted) == {"packet_id", "script"}
    valid_failure_shape = set(submitted) == {"packet_id", "failure"}
    if not valid_script_shape and not valid_failure_shape:
        raise WorkflowConflict("script_topic_submission_schema_invalid")
    topic = selected_topics[index]
    packet = topic_packet(
        run_id, business_date, topic, index, len(selected_topics),
        len(checkpoint["completed_items"]), writer_contract,
    )
    if submitted.get("packet_id") != packet["topic_input"]["packet_id"]:
        raise WorkflowConflict("script_topic_input_conflict")
    if valid_script_shape:
        script = _validate_script(submitted.get("script"), topic["topic_id"])
        item = {"kind": "script", "topic_id": script["topic_id"], "script": script}
    else:
        failure = _validate_failure(submitted.get("failure"), topic["topic_id"])
        item = {"kind": "failure", "topic_id": failure["topic_id"], "failure": failure}
    completed_items = [*checkpoint["completed_items"], item]
    updated = {**checkpoint, "completed_items": completed_items}
    if len(completed_items) < len(selected_topics):
        workflow.commit_stage(run_id, "scripts", updated, "in_progress")
        next_index = first_unfinished_index(updated)
        return {
            "complete": False,
            "checkpoint": updated,
            "handoff": topic_packet(
                run_id, business_date, selected_topics[next_index], next_index,
                len(selected_topics), len(completed_items), writer_contract,
            ),
        }
    scripts = [row["script"] for row in completed_items if row["kind"] == "script"]
    failures = [row["failure"] for row in completed_items if row["kind"] == "failure"]
    result = {
        "run_id": run_id,
        "business_date": business_date,
        "scripts": scripts,
        "failures": failures,
    }
    workflow.commit_stage(
        run_id, "scripts", result,
        "completed_with_failures" if failures else "completed",
    )
    return {"complete": True, "checkpoint": result, "scripts": result}
