#!/usr/bin/env python3
"""Public per-topic spoken-script checkpoint helpers."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from daily_workflow import WorkflowConflict, canonical


RUNTIME_SCHEMA_VERSION = 2
MATERIAL_FAILURE_REASONS = frozenset({
    "material_or_angle_insufficiency",
    "material_insufficiency",  # legacy input accepted, never generated by the new contract
})
DEFAULT_EDITING_REFERENCE = (
    Path(__file__).resolve().parents[1]
    / "config"
    / "web010_austin_voice_pack.json"
)


def load_editing_reference(path: str | Path = DEFAULT_EDITING_REFERENCE) -> dict[str, Any]:
    """Load a small style-only editing reference, never a full script or private case."""
    source = Path(path)
    try:
        value = json.loads(source.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise WorkflowConflict("editing_reference_unreadable") from error
    modules = value.get("modules") if isinstance(value, dict) else None
    if (
        not isinstance(value, dict)
        or value.get("schema_version") != RUNTIME_SCHEMA_VERSION
        or value.get("style_only") is not True
        or not isinstance(modules, list)
        or not modules
    ):
        raise WorkflowConflict("editing_reference_schema_invalid")
    normalized: list[dict[str, str]] = []
    seen: set[str] = set()
    for module in modules:
        if not isinstance(module, dict):
            raise WorkflowConflict("editing_reference_module_invalid")
        module_id = str(module.get("module_id") or "")
        name = str(module.get("name") or "")
        question = str(module.get("editing_question") or "")
        guidance = str(module.get("guidance") or "")
        if (
            not module_id or module_id in seen or not name
            or not question or not guidance
            or set(module) - {"module_id", "name", "editing_question", "guidance", "source_role"}
        ):
            raise WorkflowConflict("editing_reference_module_invalid")
        seen.add(module_id)
        normalized.append({
            "module_id": module_id,
            "name": name,
            "editing_question": question,
            "guidance": guidance,
            "source_role": str(module.get("source_role") or "approved_austin_editing_reference"),
        })
    payload = {
        "schema_version": RUNTIME_SCHEMA_VERSION,
        "style_only": True,
        "modules": normalized,
    }
    encoded = canonical(payload).encode("utf-8")
    return {
        **payload,
        "sha256": hashlib.sha256(encoded).hexdigest(),
        "content_bytes": len(encoded),
    }


def selected_topic_ids(selected_topics: list[dict[str, Any]]) -> list[str]:
    identities = [str(row.get("topic_id") or "") for row in selected_topics]
    if not identities or any(not identity for identity in identities):
        raise WorkflowConflict("scripts_selected_topics_invalid")
    if len(identities) != len(set(identities)):
        raise WorkflowConflict("scripts_selected_topics_duplicate")
    return identities


def new_checkpoint(
    run_id: str,
    business_date: str,
    selected_topics: list[dict[str, Any]],
    editing_reference: dict[str, Any],
) -> dict[str, Any]:
    return {
        "schema_version": RUNTIME_SCHEMA_VERSION,
        "run_id": run_id,
        "business_date": business_date,
        "stage": "scripts",
        "status": "in_progress",
        "selected_topic_ids": selected_topic_ids(selected_topics),
        "selected_count": len(selected_topics),
        "completed_items": [],
        "editing_reference": {
            "schema_version": editing_reference["schema_version"],
            "sha256": editing_reference["sha256"],
            "content_bytes": editing_reference["content_bytes"],
            "module_ids": [row["module_id"] for row in editing_reference["modules"]],
            "style_only": True,
        },
    }


def _validate_script(script: Any, topic_id: str) -> dict[str, str]:
    if not isinstance(script, dict) or set(script) != {
        "topic_id", "title", "hook", "structure", "body",
    }:
        raise WorkflowConflict("script_topic_submission_schema_invalid")
    if script.get("topic_id") != topic_id:
        raise WorkflowConflict("script_topic_not_current")
    if not all(str(script.get(key) or "").strip() for key in (
        "title", "hook", "structure", "body",
    )):
        raise WorkflowConflict("script_topic_submission_incomplete")
    return {key: str(script[key]) for key in (
        "topic_id", "title", "hook", "structure", "body",
    )}


def _validate_failure(failure: Any, topic_id: str) -> dict[str, str]:
    if not isinstance(failure, dict) or set(failure) != {"topic_id", "reason", "detail"}:
        raise WorkflowConflict("script_topic_failure_schema_invalid")
    if failure.get("topic_id") != topic_id:
        raise WorkflowConflict("script_topic_not_current")
    if failure.get("reason") not in MATERIAL_FAILURE_REASONS:
        raise WorkflowConflict("script_topic_failure_reason_invalid")
    if not str(failure.get("detail") or "").strip():
        raise WorkflowConflict("script_topic_failure_incomplete")
    return {
        "topic_id": str(failure["topic_id"]),
        "reason": "material_or_angle_insufficiency",
        "detail": str(failure["detail"]),
    }


def _validate_completed_items(
    items: Any,
    selected_ids: list[str],
) -> None:
    if not isinstance(items, list):
        raise WorkflowConflict("scripts_checkpoint_shape_invalid")
    selected = set(selected_ids)
    seen: set[str] = set()
    for item in items:
        if not isinstance(item, dict) or set(item) not in ({"kind", "topic_id", "script"}, {"kind", "topic_id", "failure"}):
            raise WorkflowConflict("scripts_checkpoint_item_invalid")
        topic_id = str(item.get("topic_id") or "")
        if topic_id not in selected or topic_id in seen:
            raise WorkflowConflict("scripts_checkpoint_item_identity_conflict")
        if item.get("kind") == "script":
            _validate_script(item.get("script"), topic_id)
        elif item.get("kind") == "failure":
            _validate_failure(item.get("failure"), topic_id)
        else:
            raise WorkflowConflict("scripts_checkpoint_item_kind_invalid")
        seen.add(topic_id)


def validate_checkpoint(
    checkpoint: dict[str, Any],
    run_id: str,
    business_date: str,
    selected_topics: list[dict[str, Any]],
    editing_reference: dict[str, Any],
) -> None:
    if "current_reference_selection" in checkpoint or "reference_selection" in checkpoint:
        raise WorkflowConflict("scripts_checkpoint_selector_retired")
    if (
        checkpoint.get("schema_version") != RUNTIME_SCHEMA_VERSION
        or checkpoint.get("run_id") != run_id
        or checkpoint.get("business_date") != business_date
        or checkpoint.get("stage") != "scripts"
        or checkpoint.get("status") != "in_progress"
    ):
        raise WorkflowConflict("scripts_checkpoint_identity_conflict")
    if checkpoint.get("selected_topic_ids") != selected_topic_ids(selected_topics):
        raise WorkflowConflict("scripts_checkpoint_selection_conflict")
    reference = checkpoint.get("editing_reference")
    if (
        not isinstance(reference, dict)
        or reference.get("sha256") != editing_reference.get("sha256")
        or reference.get("content_bytes") != editing_reference.get("content_bytes")
        or reference.get("style_only") is not True
    ):
        raise WorkflowConflict("scripts_checkpoint_editing_reference_conflict")
    _validate_completed_items(checkpoint.get("completed_items"), checkpoint["selected_topic_ids"])


def ensure_checkpoint(
    workflow: Any,
    run_id: str,
    business_date: str,
    selected_topics: list[dict[str, Any]],
    editing_reference: dict[str, Any],
) -> dict[str, Any]:
    existing = workflow.stage(run_id, "scripts")
    if existing is None:
        checkpoint = new_checkpoint(run_id, business_date, selected_topics, editing_reference)
        workflow.commit_stage(run_id, "scripts", checkpoint, "in_progress")
        return checkpoint
    if existing.get("status") != "in_progress":
        raise WorkflowConflict("scripts_checkpoint_not_in_progress")
    checkpoint = existing["payload"]
    validate_checkpoint(checkpoint, run_id, business_date, selected_topics, editing_reference)
    return checkpoint


def first_unfinished_index(checkpoint: dict[str, Any]) -> int:
    completed = {
        str(row.get("topic_id") or "")
        for row in checkpoint.get("completed_items", [])
    }
    for index, identity in enumerate(checkpoint["selected_topic_ids"]):
        if identity not in completed:
            return index
    return len(checkpoint["selected_topic_ids"])


def _packet_id(
    run_id: str,
    business_date: str,
    topic: dict[str, Any],
    editing_reference: dict[str, Any],
) -> str:
    basis = {
        "run_id": run_id,
        "business_date": business_date,
        "topic": topic,
        "editing_reference_sha256": editing_reference["sha256"],
    }
    return hashlib.sha256(canonical(basis).encode("utf-8")).hexdigest()


def topic_packet(
    run_id: str,
    business_date: str,
    topic: dict[str, Any],
    index: int,
    selected_count: int,
    completed_count: int,
    editing_reference: dict[str, Any],
) -> dict[str, Any]:
    packet_id = _packet_id(run_id, business_date, topic, editing_reference)
    modules = [
        {key: row[key] for key in (
            "module_id", "name", "editing_question", "guidance",
        )}
        for row in editing_reference["modules"]
    ]
    return {
        "ok": True,
        "action": "scripts_required",
        "stage": "scripts",
        "status": "waiting",
        "run_id": run_id,
        "business_date": business_date,
        "selected_topics": [topic],
        "topic_index": index,
        "selected_count": selected_count,
        "completed_count": completed_count,
        "remaining_count": selected_count - completed_count,
        "next_topic_not_exposed_until_submit": True,
        "topic_input": {
            "packet_id": packet_id,
            "topic_id": topic["topic_id"],
            "writer_owns_final_fields": ["title", "hook", "structure", "body"],
            "editing_reference_sha256": editing_reference["sha256"],
            "editing_reference": {
                "style_only": True,
                "modules": modules,
            },
            "current_topic_only": True,
            "previous_topic_body_included": False,
            "semantic_reread": {
                "current_topic_only": True,
                "questions": [
                    "是否像任何泛 AI 博主都能说的文章？",
                    "是否滑回流程、责任或验收说明？",
                    "这条题自己的论证是否真的移动了？",
                ],
                "max_rewrites": 1,
                "quality_judgment": "outer_codex_subjective_review",
            },
        },
        "editing_reference_sha256": editing_reference["sha256"],
        "editing_reference_content_bytes": editing_reference["content_bytes"],
        "editing_reference_contract": {
            "style_only": True,
            "modules_are_editing_questions_not_outline": True,
            "no_universal_content_slots": True,
        },
        "required_script_input": {
            "keys": ["packet_id", "editing_reference_sha256", "script"],
            "failure_keys": ["packet_id", "editing_reference_sha256", "failure"],
            "script_keys": ["topic_id", "title", "hook", "structure", "body"],
            "current_topic_only": True,
            "material_or_angle_insufficiency_is_item_local": True,
        },
    }


def sanitize_handoff(value: dict[str, Any]) -> dict[str, Any]:
    """Keep persisted handoffs free of retired selector/private-routing fields."""
    document = json.loads(json.dumps(value, ensure_ascii=False))
    if document.get("action") != "scripts_required":
        return document
    for key in (
        "voice_pack", "reference_selection", "topic_selector_input",
        "private_style_context", "private_case_catalog", "persona_catalog",
        "approved_exemplar_catalog",
    ):
        document.pop(key, None)
    topic_input = document.get("topic_input")
    if isinstance(topic_input, dict):
        for key in (
            "voice_pack", "reference_selection", "private_style_context",
            "private_excerpts", "approved_full_scripts",
        ):
            topic_input.pop(key, None)
    return document


def submit_topic(
    workflow: Any,
    run_id: str,
    business_date: str,
    selected_topics: list[dict[str, Any]],
    checkpoint: dict[str, Any],
    editing_reference: dict[str, Any],
    submitted: dict[str, Any],
) -> dict[str, Any]:
    validate_checkpoint(checkpoint, run_id, business_date, selected_topics, editing_reference)
    index = first_unfinished_index(checkpoint)
    if index >= len(selected_topics):
        raise WorkflowConflict("scripts_checkpoint_already_complete")
    if not isinstance(submitted, dict):
        raise WorkflowConflict("script_topic_submission_schema_invalid")
    valid_script_shape = set(submitted) == {
        "packet_id", "editing_reference_sha256", "script",
    }
    valid_failure_shape = set(submitted) == {
        "packet_id", "editing_reference_sha256", "failure",
    }
    if not valid_script_shape and not valid_failure_shape:
        raise WorkflowConflict("script_topic_submission_schema_invalid")
    topic = selected_topics[index]
    packet = topic_packet(
        run_id, business_date, topic, index, len(selected_topics),
        len(checkpoint["completed_items"]), editing_reference,
    )
    if (
        submitted.get("packet_id") != packet["topic_input"]["packet_id"]
        or submitted.get("editing_reference_sha256") != editing_reference["sha256"]
    ):
        raise WorkflowConflict("script_topic_input_conflict")
    if valid_script_shape:
        script = _validate_script(submitted.get("script"), topic["topic_id"])
        item = {"kind": "script", "topic_id": script["topic_id"], "script": script}
    else:
        failure = _validate_failure(submitted.get("failure"), topic["topic_id"])
        item = {"kind": "failure", "topic_id": failure["topic_id"], "failure": failure}
    completed_items = [*checkpoint["completed_items"], item]
    updated = {**checkpoint, "completed_items": completed_items}
    if len(completed_items) < len(selected_topics):
        workflow.commit_stage(run_id, "scripts", updated, "in_progress")
        next_index = first_unfinished_index(updated)
        return {
            "complete": False,
            "checkpoint": updated,
            "handoff": topic_packet(
                run_id, business_date, selected_topics[next_index], next_index,
                len(selected_topics), len(completed_items), editing_reference,
            ),
        }
    scripts = [row["script"] for row in completed_items if row["kind"] == "script"]
    failures = [row["failure"] for row in completed_items if row["kind"] == "failure"]
    result = {
        "run_id": run_id,
        "business_date": business_date,
        "scripts": scripts,
        "failures": failures,
    }
    workflow.commit_stage(
        run_id, "scripts", result,
        "completed_with_failures" if failures else "completed",
    )
    return {"complete": True, "checkpoint": result, "scripts": result}
