#!/usr/bin/env python3
"""Public per-topic writer checkpoints.

The writer remains one direct Automation Codex stage. The controller only
owns phase order, identity checks, persistence and projection boundaries; it
never creates article or spoken prose.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import tempfile
from pathlib import Path
from typing import Any

from daily_workflow import WorkflowConflict, canonical


RUNTIME_SCHEMA_VERSION = 4
ARTICLE_ARTIFACT_SCHEMA_VERSION = 1
WRITER_SKILL_NAME = "austin-voice-scriptwriter"
ARTICLE_REQUIRED_REFERENCES = (
    "references/khazix-writer-port.md",
    "references/austin-profile.md",
    "references/case-index.md",
    "references/voice-excerpts.md",
    "references/khazix-content-methodology.md",
    "references/khazix-style-examples.md",
)
SPOKEN_ADAPTATION_REFERENCE = "references/spoken-adaptation.md"
ALL_REQUIRED_REFERENCES = (
    *ARTICLE_REQUIRED_REFERENCES,
    SPOKEN_ADAPTATION_REFERENCE,
)
PHASE_REQUIRED_REFERENCES = {
    "article_required": ARTICLE_REQUIRED_REFERENCES,
    "spoken_adaptation_required": (SPOKEN_ADAPTATION_REFERENCE,),
}
MATERIAL_FAILURE_REASONS = frozenset({
    "material_or_angle_insufficiency",
    "material_insufficiency",  # legacy input accepted, never generated by the new contract
})
DIRECT_WRITER_STAGE_CONTRACT = {
    "schema_version": 1,
    "topology": "one_automation_codex_direct_writer_stage_per_selected_topic",
    "input_scope": [
        "one_same_run_rich_topic_card",
        "current_topic_raw_source_and_video_evidence",
        "relevant_existing_materials_and_first_party_research_when_needed",
        "optional_current_topic_author_input",
        "simple_truthfulness_requirement",
        "phase_specific_article_and_spoken_envelopes",
    ],
    "skills": [WRITER_SKILL_NAME],
    "previous_topic_body": "forbidden",
    "other_topic_identity": "forbidden",
    "editorial_batch_deliberation": "forbidden",
    "recursive_model_execution": "forbidden",
    "raw_text_persistence": "forbidden",
    "article_checkpoint": "required_before_spoken_adaptation",
    "spoken_adaptation_source": "frozen_same_topic_article_only",
    "article_artifact_persistence": "required_same_run_same_topic",
    "writer_phases": ["article_required", "spoken_adaptation_required"],
    "required_references_by_phase": {
        "article_required": list(ARTICLE_REQUIRED_REFERENCES),
        "spoken_adaptation_required": [SPOKEN_ADAPTATION_REFERENCE],
    },
}

_RETIRED_HANDOFF_KEYS = (
    "voice_pack", "reference_selection", "topic_selector_input",
    "private_style_context", "private_case_catalog", "persona_catalog",
    "approved_exemplar_catalog", "editing_reference", "editing_reference_sha256",
    "editing_reference_content_bytes", "editing_reference_contract",
)
_RETIRED_TOPIC_KEYS = (
    "voice_pack", "reference_selection", "private_style_context",
    "private_excerpts", "approved_full_scripts", "austin_private_context_raw",
    "austin_authority_read", "austin_private_context", "semantic_reread",
    "editing_reference", "editing_reference_sha256", "editing_reference_contract",
)


def load_writer_contract() -> dict[str, Any]:
    """Return the direct writer-stage contract without reading private source."""
    return json.loads(json.dumps(DIRECT_WRITER_STAGE_CONTRACT, ensure_ascii=False))


def _sha256_bytes(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def _file_manifest(path: Path, relative_path: str | None = None) -> dict[str, Any]:
    if path.is_symlink() or not path.is_file():
        raise WorkflowConflict("writer_authority_missing")
    raw = path.read_bytes()
    entry = {
        "path": str(path.resolve()),
        "sha256": _sha256_bytes(raw),
        "bytes": len(raw),
    }
    if relative_path:
        entry["relative_path"] = relative_path
    return entry


def writer_authority_manifest(
    active_root: Path | str | None = None,
    source_root: Path | str | None = None,
    *,
    require_source_parity: bool = False,
) -> dict[str, Any]:
    """Read active R4 Skill/reference provenance without any private input."""
    active = Path(active_root or (Path.home() / ".codex" / "skills" / WRITER_SKILL_NAME)).resolve()
    source = Path(source_root).resolve() if source_root else None
    skill = _file_manifest(active / "SKILL.md", "SKILL.md")
    references: list[dict[str, Any]] = []
    for relative in ALL_REQUIRED_REFERENCES:
        references.append(_file_manifest(active / relative, relative))
    source_skill: dict[str, Any] | None = None
    source_references: list[dict[str, Any]] = []
    parity = None
    if source is not None:
        source_skill = _file_manifest(source / "SKILL.md", "SKILL.md")
        for relative in ALL_REQUIRED_REFERENCES:
            source_references.append(_file_manifest(source / relative, relative))
        parity = (
            skill["sha256"] == source_skill["sha256"]
            and [row["sha256"] for row in references]
            == [row["sha256"] for row in source_references]
        )
        if require_source_parity and not parity:
            raise WorkflowConflict("writer_authority_parity_conflict")
    return {
        "skill_name": WRITER_SKILL_NAME,
        "active_skill": skill,
        "required_managed_references": references,
        "source_skill": source_skill,
        "source_managed_references": source_references,
        "source_active_exact_parity": parity,
        "required_references_by_phase": {
            phase: [
                next(row for row in references if row["relative_path"] == relative)
                for relative in relatives
            ]
            for phase, relatives in PHASE_REQUIRED_REFERENCES.items()
        },
        "input_policy": {
            "current_topic_only": True,
            "same_run_material_only": True,
            "frozen_article_required_for_spoken": True,
        },
    }


def selected_topic_ids(selected_topics: list[dict[str, Any]]) -> list[str]:
    identities = [str(row.get("topic_id") or "") for row in selected_topics]
    if not identities or any(not identity for identity in identities):
        raise WorkflowConflict("scripts_selected_topics_invalid")
    if len(identities) != len(set(identities)):
        raise WorkflowConflict("scripts_selected_topics_duplicate")
    return identities


def _writing_contract_snapshot(contract: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema_version": contract["schema_version"],
        "topology": contract["topology"],
        "skills": list(contract["skills"]),
        "previous_topic_body": contract["previous_topic_body"],
        "other_topic_identity": contract["other_topic_identity"],
        "recursive_model_execution": contract["recursive_model_execution"],
        "raw_text_persistence": contract["raw_text_persistence"],
        "article_checkpoint": contract.get("article_checkpoint"),
        "spoken_adaptation_source": contract.get("spoken_adaptation_source"),
        "article_artifact_persistence": contract.get("article_artifact_persistence"),
        "writer_phases": list(contract.get("writer_phases", [])),
        "required_references_by_phase": {
            phase: list(references)
            for phase, references in (contract.get("required_references_by_phase") or {}).items()
        },
    }


def new_checkpoint(
    run_id: str,
    business_date: str,
    selected_topics: list[dict[str, Any]],
    writer_contract: dict[str, Any],
) -> dict[str, Any]:
    return {
        "schema_version": RUNTIME_SCHEMA_VERSION,
        "run_id": run_id,
        "business_date": business_date,
        "stage": "scripts",
        "status": "in_progress",
        "selected_topic_ids": selected_topic_ids(selected_topics),
        "selected_count": len(selected_topics),
        "completed_items": [],
        "writing_contract": _writing_contract_snapshot(writer_contract),
    }


def _validate_article(article: Any, topic_id: str) -> dict[str, str]:
    if not isinstance(article, dict) or set(article) != {"topic_id", "title", "body"}:
        raise WorkflowConflict("article_topic_submission_schema_invalid")
    if article.get("topic_id") != topic_id:
        raise WorkflowConflict("article_topic_not_current")
    if not all(str(article.get(key) or "").strip() for key in ("title", "body")):
        raise WorkflowConflict("article_topic_submission_incomplete")
    return {key: str(article[key]) for key in ("topic_id", "title", "body")}


def _validate_script(script: Any, topic_id: str) -> dict[str, str]:
    if not isinstance(script, dict) or set(script) != {
        "topic_id", "title", "hook", "structure", "body",
    }:
        raise WorkflowConflict("script_topic_submission_schema_invalid")
    if script.get("topic_id") != topic_id:
        raise WorkflowConflict("script_topic_not_current")
    if not all(str(script.get(key) or "").strip() for key in (
        "title", "hook", "structure", "body",
    )):
        raise WorkflowConflict("script_topic_submission_incomplete")
    return {key: str(script[key]) for key in (
        "topic_id", "title", "hook", "structure", "body",
    )}


def _validate_failure(failure: Any, topic_id: str) -> dict[str, str]:
    if not isinstance(failure, dict) or set(failure) != {"topic_id", "reason", "detail"}:
        raise WorkflowConflict("script_topic_failure_schema_invalid")
    if failure.get("topic_id") != topic_id:
        raise WorkflowConflict("script_topic_not_current")
    if failure.get("reason") not in MATERIAL_FAILURE_REASONS:
        raise WorkflowConflict("script_topic_failure_reason_invalid")
    if not str(failure.get("detail") or "").strip():
        raise WorkflowConflict("script_topic_failure_incomplete")
    return {
        "topic_id": str(failure["topic_id"]),
        "reason": "material_or_angle_insufficiency",
        "detail": str(failure["detail"]),
    }


def article_sha256(article: dict[str, str]) -> str:
    return _sha256_bytes(canonical({
        "topic_id": article["topic_id"],
        "title": article["title"],
        "body": article["body"],
    }).encode("utf-8"))


def article_artifact_path(root: Path | str, run_id: str, topic_id: str) -> Path:
    return (
        Path(root).resolve() / run_id / "articles"
        / f"{hashlib.sha256(topic_id.encode('utf-8')).hexdigest()[:20]}.md"
    )


def _article_artifact_text(
    run_id: str, business_date: str, article: dict[str, str], digest: str,
) -> str:
    metadata = {
        "schema_version": ARTICLE_ARTIFACT_SCHEMA_VERSION,
        "kind": "austin_writer_article",
        "run_id": run_id,
        "business_date": business_date,
        "topic_id": article["topic_id"],
        "title": article["title"],
        "article_sha256": digest,
    }
    return (
        "# 完整文章 artifact\n\n"
        f"<!-- writer_article_metadata {canonical(metadata)} -->\n\n"
        "## 标题\n\n"
        f"{article['title']}\n\n"
        "## 正文\n\n"
        f"{article['body']}\n"
    )


def _atomic_write_text_once(target: Path, text: str) -> bool:
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists():
        if target.is_symlink() or not target.is_file():
            raise WorkflowConflict("article_artifact_conflict")
        if target.read_text(encoding="utf-8") == text:
            return False
        raise WorkflowConflict("article_artifact_conflict")
    descriptor, temporary = tempfile.mkstemp(prefix=f".{target.name}.", dir=target.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, target)
        directory = os.open(target.parent, os.O_RDONLY)
        try:
            os.fsync(directory)
        finally:
            os.close(directory)
    finally:
        Path(temporary).unlink(missing_ok=True)
    if target.read_text(encoding="utf-8") != text:
        raise WorkflowConflict("article_artifact_readback_unknown")
    return True


def write_article_artifact(
    root: Path | str,
    run_id: str,
    business_date: str,
    article: dict[str, str],
) -> dict[str, Any]:
    digest = article_sha256(article)
    target = article_artifact_path(root, run_id, article["topic_id"])
    text = _article_artifact_text(run_id, business_date, article, digest)
    created = _atomic_write_text_once(target, text)
    artifact_digest = _sha256_bytes(text.encode("utf-8"))
    return {
        "run_id": run_id,
        "business_date": business_date,
        "topic_id": article["topic_id"],
        "path": str(target),
        "relative_path": str(target.relative_to(Path(root).resolve() / run_id)),
        "sha256": digest,
        "artifact_sha256": artifact_digest,
        "title": article["title"],
        "created": created,
    }


def read_article_artifact(
    metadata: dict[str, Any],
    *,
    run_id: str,
    business_date: str,
    topic_id: str,
    artifact_root: Path | str | None = None,
) -> dict[str, str]:
    if not isinstance(metadata, dict):
        raise WorkflowConflict("article_checkpoint_metadata_invalid")
    if (
        metadata.get("run_id") != run_id
        or metadata.get("business_date") != business_date
        or metadata.get("topic_id") != topic_id
        or not str(metadata.get("path") or "")
        or not str(metadata.get("sha256") or "")
    ):
        raise WorkflowConflict("article_checkpoint_identity_conflict")
    path = Path(str(metadata["path"])).resolve()
    expected_name = f"{hashlib.sha256(topic_id.encode('utf-8')).hexdigest()[:20]}.md"
    if path.name != expected_name or path.parent.name != "articles" or path.parent.parent.name != run_id:
        raise WorkflowConflict("article_checkpoint_identity_conflict")
    if artifact_root is not None:
        expected = article_artifact_path(artifact_root, run_id, topic_id).resolve()
        if path != expected:
            raise WorkflowConflict("article_checkpoint_identity_conflict")
    if path.is_symlink() or not path.is_file():
        raise WorkflowConflict("article_artifact_missing")
    try:
        text = path.read_text(encoding="utf-8")
        match = re.search(r"<!-- writer_article_metadata (\{.*?\}) -->", text)
        if match is None:
            raise ValueError
        stored = json.loads(match.group(1))
        body_marker = "## 正文\n\n"
        if body_marker not in text:
            raise ValueError
        body = text.split(body_marker, 1)[1]
        if body.endswith("\n"):
            body = body[:-1]
        article = {
            "topic_id": topic_id,
            "title": str(stored.get("title") or ""),
            "body": body,
        }
        if (
            stored.get("schema_version") != ARTICLE_ARTIFACT_SCHEMA_VERSION
            or stored.get("kind") != "austin_writer_article"
            or stored.get("run_id") != run_id
            or stored.get("business_date") != business_date
            or stored.get("topic_id") != topic_id
            or stored.get("article_sha256") != metadata["sha256"]
            or (
                metadata.get("artifact_sha256")
                and _sha256_bytes(text.encode("utf-8")) != metadata["artifact_sha256"]
            )
            or article_sha256(article) != metadata["sha256"]
            or stored.get("title") != article["title"]
        ):
            raise ValueError
        return article
    except (OSError, ValueError, TypeError, json.JSONDecodeError):
        raise WorkflowConflict("article_artifact_identity_conflict") from None


def _validate_article_metadata(metadata: Any, run_id: str, business_date: str, topic_id: str) -> None:
    if not isinstance(metadata, dict):
        raise WorkflowConflict("article_checkpoint_metadata_invalid")
    if (
        metadata.get("run_id") != run_id
        or metadata.get("business_date") != business_date
        or metadata.get("topic_id") != topic_id
        or not str(metadata.get("path") or "")
        or not str(metadata.get("sha256") or "")
        or not str(metadata.get("title") or "").strip()
    ):
        raise WorkflowConflict("article_checkpoint_identity_conflict")


def _validate_completed_items(
    items: Any,
    selected_ids: list[str],
    *,
    run_id: str,
    business_date: str,
) -> None:
    if not isinstance(items, list):
        raise WorkflowConflict("scripts_checkpoint_shape_invalid")
    selected = set(selected_ids)
    phases: dict[str, set[str]] = {identity: set() for identity in selected_ids}
    for item in items:
        if not isinstance(item, dict):
            raise WorkflowConflict("scripts_checkpoint_item_invalid")
        kind = item.get("kind")
        topic_id = str(item.get("topic_id") or "")
        if topic_id not in selected:
            raise WorkflowConflict("scripts_checkpoint_item_identity_conflict")
        if kind == "article":
            if set(item) != {"kind", "topic_id", "article"} or "article" in phases[topic_id]:
                raise WorkflowConflict("scripts_checkpoint_item_invalid")
            _validate_article_metadata(item.get("article"), run_id, business_date, topic_id)
            phases[topic_id].add("article")
        elif kind == "spoken":
            if set(item) != {"kind", "topic_id", "article", "script"} or "spoken" in phases[topic_id]:
                raise WorkflowConflict("scripts_checkpoint_item_invalid")
            _validate_article_metadata(item.get("article"), run_id, business_date, topic_id)
            _validate_script(item.get("script"), topic_id)
            if "article" not in phases[topic_id]:
                raise WorkflowConflict("scripts_checkpoint_item_identity_conflict")
            phases[topic_id].add("spoken")
        elif kind == "failure":
            if set(item) != {"kind", "topic_id", "phase", "failure"} or phases[topic_id] & {"failure", "spoken"}:
                raise WorkflowConflict("scripts_checkpoint_item_invalid")
            if item.get("phase") not in {"article", "spoken"}:
                raise WorkflowConflict("scripts_checkpoint_item_phase_invalid")
            if item.get("phase") == "spoken" and "article" not in phases[topic_id]:
                raise WorkflowConflict("scripts_checkpoint_item_identity_conflict")
            _validate_failure(item.get("failure"), topic_id)
            phases[topic_id].add("failure")
        else:
            raise WorkflowConflict("scripts_checkpoint_item_kind_invalid")
    for topic_id, state in phases.items():
        if "failure" in state and ("article" in state or "spoken" in state):
            raise WorkflowConflict("scripts_checkpoint_item_identity_conflict")


def validate_checkpoint(
    checkpoint: dict[str, Any],
    run_id: str,
    business_date: str,
    selected_topics: list[dict[str, Any]],
    writer_contract: dict[str, Any],
) -> None:
    if any(key in checkpoint for key in (
        "current_reference_selection", "reference_selection", "private_authority",
        "private_style_context", "austin_private_context", "austin_authority_read",
        "editing_reference", "editing_reference_contract",
    )):
        raise WorkflowConflict("scripts_checkpoint_private_context_retired")
    if (
        checkpoint.get("schema_version") != RUNTIME_SCHEMA_VERSION
        or checkpoint.get("run_id") != run_id
        or checkpoint.get("business_date") != business_date
        or checkpoint.get("stage") != "scripts"
        or checkpoint.get("status") != "in_progress"
    ):
        raise WorkflowConflict("scripts_checkpoint_identity_conflict")
    if checkpoint.get("selected_topic_ids") != selected_topic_ids(selected_topics):
        raise WorkflowConflict("scripts_checkpoint_selection_conflict")
    contract = checkpoint.get("writing_contract")
    if contract != _writing_contract_snapshot(writer_contract):
        raise WorkflowConflict("scripts_checkpoint_writing_contract_conflict")
    _validate_completed_items(
        checkpoint.get("completed_items"), checkpoint["selected_topic_ids"],
        run_id=run_id, business_date=business_date,
    )


def ensure_checkpoint(
    workflow: Any,
    run_id: str,
    business_date: str,
    selected_topics: list[dict[str, Any]],
    writer_contract: dict[str, Any],
) -> dict[str, Any]:
    existing = workflow.stage(run_id, "scripts")
    if existing is None:
        checkpoint = new_checkpoint(run_id, business_date, selected_topics, writer_contract)
        workflow.commit_stage(run_id, "scripts", checkpoint, "in_progress")
        return checkpoint
    if existing.get("status") != "in_progress":
        raise WorkflowConflict("scripts_checkpoint_not_in_progress")
    checkpoint = existing["payload"]
    validate_checkpoint(checkpoint, run_id, business_date, selected_topics, writer_contract)
    return checkpoint


def _topic_entries(checkpoint: dict[str, Any], topic_id: str) -> dict[str, dict[str, Any] | None]:
    state: dict[str, dict[str, Any] | None] = {
        "article": None, "spoken": None, "failure": None,
    }
    for item in checkpoint.get("completed_items", []):
        if item.get("topic_id") != topic_id:
            continue
        kind = item.get("kind")
        if kind in state:
            state[kind] = item
    return state


def topic_phase(checkpoint: dict[str, Any], topic_id: str) -> str:
    state = _topic_entries(checkpoint, topic_id)
    if state["failure"] is not None or state["spoken"] is not None:
        return "complete"
    if state["article"] is None:
        return "article_required"
    return "spoken_adaptation_required"


def terminal_topic_count(checkpoint: dict[str, Any]) -> int:
    return sum(
        topic_phase(checkpoint, topic_id) == "complete"
        for topic_id in checkpoint.get("selected_topic_ids", [])
    )


def first_unfinished_index(checkpoint: dict[str, Any]) -> int:
    for index, identity in enumerate(checkpoint["selected_topic_ids"]):
        if topic_phase(checkpoint, identity) != "complete":
            return index
    return len(checkpoint["selected_topic_ids"])


def _packet_id(
    run_id: str,
    business_date: str,
    topic: dict[str, Any],
    phase: str,
) -> str:
    basis = {
        "run_id": run_id,
        "business_date": business_date,
        "topic": topic,
        "phase": phase,
    }
    return hashlib.sha256(canonical(basis).encode("utf-8")).hexdigest()


def topic_packet(
    run_id: str,
    business_date: str,
    topic: dict[str, Any],
    index: int,
    selected_count: int,
    completed_count: int,
    writer_contract: dict[str, Any],
    *,
    checkpoint: dict[str, Any] | None = None,
    writer_authority: dict[str, Any] | None = None,
    artifact_root: Path | str | None = None,
) -> dict[str, Any]:
    topic_id = str(topic.get("topic_id") or "")
    if checkpoint is not None:
        if not isinstance(checkpoint.get("selected_topic_ids"), list):
            raise WorkflowConflict("scripts_checkpoint_shape_invalid")
        expected_index = first_unfinished_index(checkpoint)
        if index != expected_index:
            raise WorkflowConflict("scripts_topic_not_current")
    phase = topic_phase(checkpoint, topic_id) if checkpoint is not None else "article_required"
    if phase == "complete":
        raise WorkflowConflict("scripts_checkpoint_already_complete")
    packet_id = _packet_id(run_id, business_date, topic, phase)
    # Article creation receives the rich current topic card and its same-run
    # evidence. Adaptation receives only identity plus the frozen artifact;
    # carrying the original topic here would silently reintroduce the old
    # raw/video/editorial context on a retry.
    packet_topic = topic if phase == "article_required" else {"topic_id": topic_id}
    packet: dict[str, Any] = {
        "ok": True,
        "action": phase,
        "stage": "scripts",
        "status": "waiting",
        "run_id": run_id,
        "business_date": business_date,
        "selected_topics": [packet_topic],
        "topic_index": index,
        "selected_count": selected_count,
        "completed_count": completed_count,
        "remaining_count": selected_count - completed_count,
        "next_topic_not_exposed_until_submit": True,
        "topic_input": {
            "packet_id": packet_id,
            "topic_id": topic_id,
            "phase": phase,
            "writer_owns_final_fields": (
                ["article_title", "article_body"]
                if phase == "article_required"
                else ["body", "title", "hook", "structure"]
            ),
            "current_topic_only": True,
            "previous_topic_body_included": False,
            "required_references": list(PHASE_REQUIRED_REFERENCES[phase]),
        },
    }
    if writer_authority is not None:
        packet["writer_authority"] = writer_authority
        active_skill = writer_authority["active_skill"]["path"]
        active_root = Path(active_skill).parent
        packet["owner_invocation"] = {
            "skill_entrypoint": active_skill,
            "phase": phase,
            "reference_paths": [
                str(active_root / relative)
                for relative in PHASE_REQUIRED_REFERENCES[phase]
            ],
            "instruction": (
                "Open the complete active SKILL.md and follow its existing reading order. "
                "Open the full current article references and this topic's same-run raw "
                "materials. Open relevant cases or original voice samples when the Skill "
                "calls for them; resolve their paths relative to the active Skill. "
                "Apply the Skill, then submit required_article_input."
                if phase == "article_required" else
                "Open the complete frozen article at topic_input.article_artifact.path "
                "and the full spoken-adaptation reference. Apply that phase and submit "
                "required_spoken_adaptation_input."
            ),
            "read_evidence_boundary": (
                "Hashes, file inventories and historical reads do not establish current "
                "Skill application or complete content reading."
            ),
            "tools": {
                "file_reads": "available",
                "first_party_research": "permitted_as_required_by_skill",
                "recursive_model_execution": "forbidden",
            },
        }
    if phase == "article_required":
        packet["required_article_input"] = {
            "keys": ["packet_id", "article"],
            "article_keys": ["topic_id", "title", "body"],
            "failure_keys": ["packet_id", "failure"],
            "current_topic_only": True,
            "material_or_angle_insufficiency_is_item_local": True,
        }
    else:
        article_item = _topic_entries(checkpoint or {}, topic_id)["article"]
        if not article_item:
            raise WorkflowConflict("spoken_before_article")
        metadata = article_item["article"]
        _validate_article_metadata(metadata, run_id, business_date, topic_id)
        if artifact_root is not None:
            read_article_artifact(
                metadata, run_id=run_id, business_date=business_date, topic_id=topic_id,
                artifact_root=artifact_root,
            )
        packet["topic_input"]["article_artifact"] = {
            key: metadata[key]
            for key in ("run_id", "business_date", "topic_id", "path", "relative_path", "sha256", "artifact_sha256", "title")
            if key in metadata
        }
        packet["topic_input"]["spoken_adaptation_contract"] = {
            "source": "frozen_same_topic_article_only",
            "article_sha256": metadata["sha256"],
            "article_artifact_required": True,
            "read_complete_artifact_body": True,
        }
        packet["required_spoken_adaptation_input"] = {
            "keys": ["packet_id", "article_sha256", "script"],
            "failure_keys": ["packet_id", "article_sha256", "failure"],
            "script_keys": ["topic_id", "title", "hook", "structure", "body"],
            "current_topic_only": True,
            "frozen_article_only": True,
            "material_or_angle_insufficiency_is_item_local": True,
        }
    return packet


def sanitize_handoff(value: dict[str, Any]) -> dict[str, Any]:
    """Keep persisted handoffs free of retired selector/style/private-routing fields."""
    document = json.loads(json.dumps(value, ensure_ascii=False))
    if document.get("action") not in {"article_required", "spoken_adaptation_required", "scripts_required"}:
        return document
    for key in _RETIRED_HANDOFF_KEYS:
        document.pop(key, None)
    topic_input = document.get("topic_input")
    if isinstance(topic_input, dict):
        for key in _RETIRED_TOPIC_KEYS:
            topic_input.pop(key, None)
    return document


def _append_item(checkpoint: dict[str, Any], item: dict[str, Any]) -> dict[str, Any]:
    return {**checkpoint, "completed_items": [*checkpoint["completed_items"], item]}


def _result_or_next(
    workflow: Any,
    run_id: str,
    business_date: str,
    selected_topics: list[dict[str, Any]],
    updated: dict[str, Any],
    writer_contract: dict[str, Any],
    *,
    writer_authority: dict[str, Any] | None,
    artifact_root: Path | str | None,
) -> dict[str, Any]:
    next_index = first_unfinished_index(updated)
    if next_index < len(selected_topics):
        handoff = topic_packet(
            run_id, business_date, selected_topics[next_index], next_index,
            len(selected_topics), terminal_topic_count(updated), writer_contract,
            checkpoint=updated, writer_authority=writer_authority,
            artifact_root=artifact_root,
        )
        workflow.commit_stage(run_id, "scripts", updated, "in_progress")
        return {
            "complete": False,
            "checkpoint": updated,
            "handoff": handoff,
        }
    scripts = [row["script"] for row in updated["completed_items"] if row.get("kind") == "spoken"]
    failures = [row["failure"] for row in updated["completed_items"] if row.get("kind") == "failure"]
    result = {
        "run_id": run_id,
        "business_date": business_date,
        "scripts": scripts,
        "failures": failures,
    }
    workflow.commit_stage(
        run_id, "scripts", result,
        "completed_with_failures" if failures else "completed",
    )
    return {"complete": True, "checkpoint": result, "scripts": result}


def submit_article(
    workflow: Any,
    run_id: str,
    business_date: str,
    selected_topics: list[dict[str, Any]],
    checkpoint: dict[str, Any],
    writer_contract: dict[str, Any],
    submitted: dict[str, Any],
    *,
    artifact_root: Path | str,
    writer_authority: dict[str, Any] | None = None,
) -> dict[str, Any]:
    validate_checkpoint(checkpoint, run_id, business_date, selected_topics, writer_contract)
    index = first_unfinished_index(checkpoint)
    if index >= len(selected_topics):
        raise WorkflowConflict("scripts_checkpoint_already_complete")
    topic = selected_topics[index]
    topic_id = topic["topic_id"]
    phase = topic_phase(checkpoint, topic_id)
    if phase == "spoken_adaptation_required" and isinstance(submitted, dict):
        # A retry of the already committed article is idempotent only when it
        # is byte-for-byte the same article. It returns the frozen adaptation
        # packet and never regenerates or rewrites the artifact.
        if set(submitted) == {"packet_id", "article"}:
            article_item = _topic_entries(checkpoint, topic_id)["article"]
            metadata = article_item["article"] if article_item else None
            packet = topic_packet(
                run_id, business_date, topic, index, len(selected_topics),
                terminal_topic_count(checkpoint), writer_contract, checkpoint=checkpoint,
                writer_authority=writer_authority, artifact_root=artifact_root,
            )
            article = _validate_article(submitted.get("article"), topic_id)
            if (
                submitted.get("packet_id")
                == _packet_id(run_id, business_date, topic, "article_required")
                and metadata is not None
                and article_sha256(article) == metadata.get("sha256")
            ):
                return {
                    "complete": False,
                    "checkpoint": checkpoint,
                    "handoff": packet,
                }
        raise WorkflowConflict("article_checkpoint_already_complete")
    if phase != "article_required":
        raise WorkflowConflict("article_checkpoint_already_complete")
    if not isinstance(submitted, dict):
        raise WorkflowConflict("article_topic_submission_schema_invalid")
    valid_article = set(submitted) == {"packet_id", "article"}
    valid_failure = set(submitted) == {"packet_id", "failure"}
    if not valid_article and not valid_failure:
        raise WorkflowConflict("article_topic_submission_schema_invalid")
    packet = topic_packet(
        run_id, business_date, topic, index, len(selected_topics),
        terminal_topic_count(checkpoint), writer_contract, checkpoint=checkpoint,
        writer_authority=writer_authority,
    )
    if submitted.get("packet_id") != packet["topic_input"]["packet_id"]:
        raise WorkflowConflict("article_topic_input_conflict")
    created_path: Path | None = None
    if valid_article:
        article = _validate_article(submitted.get("article"), topic_id)
        metadata = write_article_artifact(artifact_root, run_id, business_date, article)
        if metadata.get("created"):
            created_path = Path(metadata["path"])
        metadata.pop("created", None)
        item = {"kind": "article", "topic_id": topic_id, "article": metadata}
    else:
        failure = _validate_failure(submitted.get("failure"), topic_id)
        item = {"kind": "failure", "topic_id": topic_id, "phase": "article", "failure": failure}
    updated = _append_item(checkpoint, item)
    try:
        outcome = _result_or_next(
            workflow, run_id, business_date, selected_topics, updated, writer_contract,
            writer_authority=writer_authority, artifact_root=artifact_root,
        )
    except Exception:
        if created_path is not None:
            created_path.unlink(missing_ok=True)
        raise
    return outcome


def submit_spoken_adaptation(
    workflow: Any,
    run_id: str,
    business_date: str,
    selected_topics: list[dict[str, Any]],
    checkpoint: dict[str, Any],
    writer_contract: dict[str, Any],
    submitted: dict[str, Any],
    *,
    artifact_root: Path | str | None = None,
    writer_authority: dict[str, Any] | None = None,
) -> dict[str, Any]:
    validate_checkpoint(checkpoint, run_id, business_date, selected_topics, writer_contract)
    index = first_unfinished_index(checkpoint)
    if index >= len(selected_topics):
        raise WorkflowConflict("scripts_checkpoint_already_complete")
    topic = selected_topics[index]
    topic_id = topic["topic_id"]
    phase = topic_phase(checkpoint, topic_id)
    if phase == "article_required":
        raise WorkflowConflict("spoken_before_article")
    if phase != "spoken_adaptation_required":
        raise WorkflowConflict("spoken_checkpoint_already_complete")
    article_item = _topic_entries(checkpoint, topic_id)["article"]
    if not article_item:
        raise WorkflowConflict("spoken_before_article")
    metadata = article_item["article"]
    packet = topic_packet(
        run_id, business_date, topic, index, len(selected_topics),
        terminal_topic_count(checkpoint), writer_contract, checkpoint=checkpoint,
        writer_authority=writer_authority, artifact_root=artifact_root,
    )
    if not isinstance(submitted, dict):
        raise WorkflowConflict("spoken_adaptation_submission_schema_invalid")
    valid_script = set(submitted) == {"packet_id", "article_sha256", "script"}
    valid_failure = set(submitted) == {"packet_id", "article_sha256", "failure"}
    if not valid_script and not valid_failure:
        raise WorkflowConflict("spoken_adaptation_submission_schema_invalid")
    if submitted.get("packet_id") != packet["topic_input"]["packet_id"]:
        raise WorkflowConflict("spoken_adaptation_input_conflict")
    if submitted.get("article_sha256") != metadata.get("sha256"):
        raise WorkflowConflict("spoken_adaptation_article_identity_conflict")
    read_article_artifact(
        metadata, run_id=run_id, business_date=business_date, topic_id=topic_id,
        artifact_root=artifact_root,
    )
    if valid_script:
        script = _validate_script(submitted.get("script"), topic_id)
        item = {
            "kind": "spoken", "topic_id": topic_id,
            "article": metadata, "script": script,
        }
    else:
        failure = _validate_failure(submitted.get("failure"), topic_id)
        item = {
            "kind": "failure", "topic_id": topic_id, "phase": "spoken",
            "failure": failure,
        }
    updated = _append_item(checkpoint, item)
    return _result_or_next(
        workflow, run_id, business_date, selected_topics, updated, writer_contract,
        writer_authority=writer_authority, artifact_root=artifact_root,
    )


# Kept as an explicit alias for external code that imported the old operation.
# It now enforces the spoken-adaptation envelope and cannot bypass the article.
submit_topic = submit_spoken_adaptation
